language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"

compiler: gcc
sudo: false

os:
  - linux
  - osx

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - git submodule update --init --recursive
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CC="gcc-4.7";
      export CXX="g++-4.7";
      export LINK="gcc-4.7";
      export LINKXX="g++-4.7";
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test

after_success:
  - if [ $TRAVIS_OS_NAME == "linux" ] && [ $NODE_VERSION == "4" ]; then
      npm run-script coverage;
    fi

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8dddd234a441d0d07664
    on_success: change
